---
- name: install AD-Domain-Services
  win_feature:
      name: AD-Domain-Services
      state: present

- name: set up AD controller
  win_domain:
      safe_mode_password: "{{ad_safe_mode_password}}" # required. safe mode password for the domain controller
      dns_domain_name: "{{ad_domain_name}}" # required. the DNS name of the domain which should exist and be reachable or reside on the target Windows host

- name: reboot the instance
  win_reboot:
      reboot_timeout: 300 

- name: list domain
  win_command: nltest /dclist:"{{ ad_domain_name }}"